# Generated by Django 5.0.1 on 2024-01-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('regions', '0001_initial'),
        ('trails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trail_country', to='countries.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trail_region', to='regions.region'),
            preserve_default=False,
        ),
    ]
