# Generated by Django 5.0.1 on 2024-01-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_trail_country_trail_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='country',
        ),
    ]
