# Generated by Django 5.0.1 on 2024-01-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
        ('trails', '0005_trail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='trail_reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_reviews', to='reviews.review'),
        ),
    ]
