# Generated by Django 5.0.1 on 2024-01-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_trail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
