# Generated by Django 5.0.1 on 2024-01-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_alter_trail_trail_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='trail_reviews',
        ),
    ]
