# Generated by Django 5.0.1 on 2024-01-15 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('ability', models.CharField(choices=[(2, 'Casual Stroller'), (3, 'Average Pace'), (4, 'On a Mission')], default=2, max_length=30)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hikers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
