# Generated by Django 5.0.1 on 2024-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='ability',
            field=models.CharField(choices=[(1, 'Casual Stroller'), (2, 'Average Pace'), (3, 'On a Mission')], default=2, max_length=30),
        ),
    ]
