# Generated by Django 5.0.1 on 2024-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0002_alter_hiker_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='ability',
            field=models.CharField(choices=[('2', 'Casual Stroller'), ('3', 'Average Pace'), ('4', 'On a Mission')], default=2, max_length=30),
        ),
    ]
