# Generated by Django 5.0.1 on 2024-01-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0003_alter_hiker_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiker',
            name='picture',
            field=models.CharField(blank=True, null=True),
        ),
    ]
